# https://quarto.org/docs/projects/quarto-projects.html
project:
  type: website
  output-dir: _site

# https://quarto.org/docs/websites/
website:
  title: Quarto Julia Template
  page-navigation: true
  bread-crumbs: true
  back-to-top-navigation: true
  repo-url: https://github.com/sosiristseng/template-quarto-literate
  site-url: https://sosiristseng.github.io/template-quarto-literate/
  search:
    show-item-context: true
    type: overlay
  sidebar:
    style: docked
    collapse-level: 2
    align: left
    search: true
    contents:
      - index.ipynb
      - symbolic.ipynb
      - pythonplot.ipynb
      - section: "Subdir"
        contents:
          - sub/plots.ipynb
      - about.qmd
    tools:
      - icon: github
        href: https://github.com/sosiristseng/template-quarto-literate

# bibliography: references.bib

# https://quarto.org/docs/output-formats/html-basics.html
format:
  html:
    respect-user-color-scheme: true
    toc: true
    theme:
      light: cosmo
      dark: darkly
    code-copy: true
    code-overflow: wrap
    grid:
      sidebar-width: 250px
      body-width: 1200px
      margin-width: 300px
    keep-md: true
    # css: styles.css
execute:
  output: asis
